#!/bin/sh
set -e

output_file="ublock/import_urls"
url_prefix="https://raw.githubusercontent.com/DisabledOctopus/block-gafam/master/ublock/"

{
for file in domains/*; do
	corp="$(printf "%s" "$file" | sed "s/domains\///")"
	printf "%s%s\n" "$url_prefix" "$corp"
done
} > "$output_file"
