#!/bin/sh
set -e

for file in domains/*; do

	company="$(printf "%s" "$file" | sed "s/domains\///")"
	title="$(printf "%s" "$company" | sed "s/^./\U&/")"

	printf "Generating %s list...\n" "$company"

	sed "s/^/||/ ; 
		s/$/\^/ ;
		1 i\# Title: $title\n" "$file" >ublock/"$company"

done
